"""add requests and request_attempts tables, rename category enum

Revision ID: 1e9d3183d503
Revises: 647b808c17df
Create Date: 2026-09-25 11:02:11.440932

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e9d3183d503"
down_revision: str | Sequence[str] | None = "647b808c17df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "request_type", sa.Enum("CATALOG_CREATION", name="requesttypeenum"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "QUEUED", "PROCESSING", "COMPLETED", "FAILED", name="requeststatusenum"
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_item_id", sa.Integer(), nullable=True),
        sa.Column("locked_by", sa.String(length=64), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "request_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("STARTED", "SUCCEEDED", "FAILED", name="attemptstatusenum"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("success_message", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status != 'FAILED' OR error_message IS NOT NULL",
            name="ck_request_attempts_failed_has_error_message",
        ),
        sa.CheckConstraint(
            "status != 'SUCCEEDED' OR success_message IS NOT NULL",
            name="ck_request_attempts_succeeded_has_success_message",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("ALTER TYPE softwarecategory RENAME TO softwarecategoryenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE softwarecategoryenum RENAME TO softwarecategory")
    op.drop_table("request_attempts")
    op.drop_table("requests")
    sa.Enum(name="attemptstatusenum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="requeststatusenum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="requesttypeenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
