"""add duplicate checks and pairs tables

Revision ID: 43c2bd8e4a65
Revises: 624de2e35537
Create Date: 2026-09-29 13:17:28.664671

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43c2bd8e4a65"
down_revision: str | Sequence[str] | None = "624de2e35537"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duplicate_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_names", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("duplicate_threshold", sa.Float(), nullable=False),
        sa.Column("review_threshold", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "duplicate_pairs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("check_id", sa.UUID(), nullable=False),
        sa.Column("name_a", sa.String(length=255), nullable=False),
        sa.Column("name_b", sa.String(length=255), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("LIKELY_DUPLICATE", "REVIEW_MANUALLY", name="duplicateverdictenum"),
            nullable=False,
        ),
        sa.Column("is_duplicate", sa.Boolean(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("overlapping_features", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("explained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["check_id"],
            ["duplicate_checks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("duplicate_pairs")
    op.drop_table("duplicate_checks")
    sa.Enum(name="duplicateverdictenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
