"""add trace_id to requests

Revision ID: 53d3cd0d67e2
Revises: 43c2bd8e4a65
Create Date: 2026-10-02 11:36:23.506931

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53d3cd0d67e2"
down_revision: str | Sequence[str] | None = "43c2bd8e4a65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("trace_id", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "trace_id")
    # ### end Alembic commands ###
