"""add trace_context to requests

Revision ID: a16320a23aed
Revises: 53d3cd0d67e2
Create Date: 2026-10-02 13:24:25.259455

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a16320a23aed"
down_revision: str | Sequence[str] | None = "53d3cd0d67e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("trace_context", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "trace_context")
    # ### end Alembic commands ###
