"""add llm_calls table

Revision ID: b24b03bbc72a
Revises: 1e9d3183d503
Create Date: 2026-09-25 15:47:01.386682

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b24b03bbc72a"
down_revision: str | Sequence[str] | None = "1e9d3183d503"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("CLASSIFICATION", "EMBEDDING", "EXPLAIN_DUPLICATE", name="llmcallpurposeenum"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=8, asdecimal=False), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("SUCCESS", "ERROR", name="llmcallstatusenum"), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_calls")
    sa.Enum(name="llmcallstatusenum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="llmcallpurposeenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
